COURSE_CATALOG = {
    "accounting_courses": {
        "ACC 201": "Financial Accounting",
        "ACC 202": "Managerial Accounting",
        "ACC 310": "Intermediate Accounting I",
        "ACC 311": "Intermediate Accounting II",
        "ACC 420": "Auditing",
    },
    "aviation_courses": {
        "AVI 101": "Introduction to Aviation",
        "AVI 120": "Private Pilot Ground School",
        "AVI 230": "Instrument Flight Theory",
        "AVI 310": "Aviation Safety",
        "AVI 360": "Air Traffic Systems",
    },
    "biology_courses": {
        "BIO 110": "Principles of Biology I",
        "BIO 111": "Principles of Biology II",
        "BIO 220": "Genetics",
        "BIO 330": "Microbiology",
        "BIO 410": "Ecology",
    },
    "business_courses": {
        "BUS 101": "Introduction to Business",
        "ACC 201": "Financial Accounting",
        "ECO 201": "Microeconomics",
        "MKT 301": "Principles of Marketing",
        "FIN 320": "Corporate Finance",
    },
    "communication_courses": {
        "COM 101": "Public Speaking",
        "COM 210": "Interpersonal Communication",
        "COM 230": "Mass Media and Society",
        "COM 320": "Organizational Communication",
        "COM 350": "Digital Media Production",
    },
    "computer_science_courses": {
        "CS 110": "Introduction to Programming",
        "CS 220": "Data Structures",
        "CS 230": "Computer Organization",
        "CS 310": "Algorithms",
        "CS 340": "Database Systems",
    },
    "criminal_justice_courses": {
        "CRJ 101": "Introduction to Criminal Justice",
        "CRJ 210": "Criminology",
        "CRJ 230": "Policing in America",
        "CRJ 320": "Corrections",
        "CRJ 410": "Criminal Law",
    },
    "cybersecurity_courses": {
        "CYB 210": "Introduction to Cybersecurity",
        "CYB 220": "Network Security",
        "CYB 310": "Ethical Hacking",
        "CYB 320": "Digital Forensics",
        "CYB 410": "Security Operations",
    },
    "economics_courses": {
        "ECO 201": "Microeconomics",
        "ECO 202": "Macroeconomics",
        "ECO 310": "Intermediate Microeconomics",
        "ECO 311": "Intermediate Macroeconomics",
        "ECO 420": "Econometrics",
    },
    "education_courses": {
        "EDU 200": "Foundations of Education",
        "EDU 240": "Educational Psychology",
        "EDU 300": "Classroom Management",
        "EDU 330": "Assessment and Instruction",
        "EDU 410": "Student Teaching Seminar",
    },
    "engineering_courses": {
        "ENGR 101": "Introduction to Engineering",
        "ENGR 201": "Statics",
        "ENGR 220": "Dynamics",
        "ENGR 250": "Thermodynamics",
        "ENGR 310": "Circuits",
    },
    "english_courses": {
        "ENG 101": "English Composition I",
        "ENG 102": "English Composition II",
        "ENG 220": "Introduction to Literature",
        "ENG 320": "American Literature",
        "ENG 410": "Advanced Writing",
    },
    "exercise_science_courses": {
        "EXS 101": "Introduction to Exercise Science",
        "EXS 220": "Kinesiology",
        "EXS 230": "Exercise Physiology",
        "EXS 320": "Biomechanics",
        "EXS 410": "Strength and Conditioning",
    },
    "finance_courses": {
        "FIN 301": "Principles of Finance",
        "FIN 320": "Corporate Finance",
        "FIN 330": "Investments",
        "FIN 410": "Financial Markets",
        "FIN 420": "International Finance",
    },
    "general_courses": {
        "ENG 101": "English Composition I",
        "MAT 103": "College Algebra",
        "BIO 100": "General Biology",
        "HIS 201": "U.S. History",
        "PSY 101": "Introduction to Psychology",
    },
    "management_courses": {
        "MGT 301": "Principles of Management",
        "MGT 320": "Organizational Behavior",
        "MGT 330": "Human Resource Management",
        "MGT 410": "Operations Management",
        "MGT 420": "Strategic Management",
    },
    "marine_science_courses": {
        "MSC 101": "Introduction to Marine Science",
        "MSC 220": "Oceanography",
        "MSC 240": "Marine Ecology",
        "MSC 320": "Marine Conservation",
        "MSC 410": "Coastal Processes",
    },
    "marketing_courses": {
        "MKT 301": "Principles of Marketing",
        "MKT 320": "Consumer Behavior",
        "MKT 330": "Digital Marketing",
        "MKT 410": "Marketing Research",
        "MKT 420": "Strategic Marketing",
    },
    "music_courses": {
        "MUS 101": "Music Appreciation",
        "MUS 120": "Music Theory I",
        "MUS 121": "Music Theory II",
        "MUS 220": "History of Western Music",
        "MUS 410": "Senior Recital",
    },
    "nursing_courses": {
        "NUR 201": "Foundations of Nursing",
        "NUR 220": "Health Assessment",
        "NUR 301": "Adult Health Nursing",
        "NUR 320": "Pharmacology",
        "NUR 410": "Community Health Nursing",
    },
    "philosophy_courses": {
        "PHI 101": "Introduction to Philosophy",
        "PHI 210": "Ethics",
        "PHI 220": "Logic",
        "PHI 320": "Political Philosophy",
        "PHI 410": "Philosophy of Mind",
    },
    "political_science_courses": {
        "POL 101": "Introduction to Political Science",
        "POL 220": "American Government",
        "POL 230": "International Relations",
        "POL 320": "Comparative Politics",
        "POL 410": "Public Policy",
    },
    "psychology_courses": {
        "PSY 101": "Introduction to Psychology",
        "PSY 220": "Developmental Psychology",
        "PSY 230": "Abnormal Psychology",
        "PSY 310": "Cognitive Psychology",
        "PSY 340": "Research Methods in Psychology",
    },
}
